-- ════════════════════════════════════════════════════════════════════════════
-- Observatorio 360 · Esquema de resultados de estudiantes
--
-- QUÉ GUARDA Y QUÉ NO
-- Guarda **solo resultados agregados**: una fila por combinación de nivel,
-- grupo e indicador. No guarda ni una respuesta individual, ni un identificador
-- de estudiante, ni el nombre de nadie. Los datos crudos no salen de la máquina
-- de quien procesa: lo que se publica es lo que ya se puede mostrar.
--
-- POR QUÉ ASÍ
-- Son datos de salud mental de menores de edad. El riesgo no es que alguien vea
-- un promedio; es que alguien reconstruya el caso de un estudiante concreto. Con
-- agregados y un mínimo de 10 por grupo, eso no es posible ni con acceso total a
-- la base.
--
-- SEGURIDAD
--   · RLS activo en todas las tablas.
--   · El rol anónimo (la clave que viaja en el cliente) SOLO puede leer, y solo
--     las filas marcadas como publicables.
--   · Escribir requiere la clave service_role, que se queda en el equipo de
--     quien publica y nunca se despliega.
--   · Un CHECK a nivel de base rechaza cualquier fila con n < 10. La regla de
--     privacidad deja de depender de que el código de la aplicación la respete.
--
-- Ejecutar en: Supabase Dashboard → SQL Editor → Run.
-- Es idempotente: se puede volver a ejecutar sin perder datos.
--
-- ESTADO ACTUAL Y MIGRACIONES
-- Este archivo describe el estado vigente completo del esquema. Los cambios
-- incrementales sobre una base ya creada viven en `supabase/migraciones/`.
-- Ya incluye la migración 2026-10-07 (corridas por módulo: el público solo lee
-- la última corrida publicada de cada módulo; nivel 'cuidadores'; ningún
-- identificador E/C/N; mensajes por módulo) y la 2026-10-07c (ningún conteo de
-- casos; alertas con estado solo donde hay cifra) y la 2026-10-10 (el usuario
-- cargador lee también las corridas ocultas, para la vista previa del equipo) y
-- la 2026-10-10b (nivel 'triangulacion'; el público nunca lee la triangulación,
-- solo el usuario de carga). Volver a ejecutarlo NO reabre las corridas viejas al
-- público.
-- ════════════════════════════════════════════════════════════════════════════

-- ── 0. Esquema propio, para no mezclarse con lo que ya existe ──────────────
CREATE SCHEMA IF NOT EXISTS obs360;

-- El mínimo de casos por grupo vive en la base, no solo en Python.
CREATE OR REPLACE FUNCTION obs360.min_grupo() RETURNS integer
  LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path = obs360, pg_temp
  AS $$ SELECT 10 $$;

COMMENT ON FUNCTION obs360.min_grupo() IS
  'Mínimo de estudiantes por grupo para poder publicar una cifra. '
  'Debe coincidir con catalog.MIN_GROUP_N en la aplicación.';

-- ── 1. Corridas del análisis ───────────────────────────────────────────────
-- Cada publicación es una corrida trazable: qué versión del análisis produjo
-- estas cifras. Sin esto, un número en la plataforma no se puede auditar.
CREATE TABLE IF NOT EXISTS obs360.corridas (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creada_en        TIMESTAMPTZ NOT NULL DEFAULT now(),
    modulo           TEXT NOT NULL DEFAULT 'estudiantes',
    version_analisis TEXT NOT NULL,          -- hash de estructura + fecha
    n_secundaria     INTEGER,
    n_primaria       INTEGER,
    notas            TEXT,
    publicada        BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT corridas_modulo_no_vacio CHECK (length(trim(modulo)) > 0)
);

COMMENT ON TABLE obs360.corridas IS
  'Una fila por publicación de resultados. `publicada` controla qué ve el '
  'público: una corrida entra en false, se revisa y se abre cuando el equipo '
  'la aprueba.';

-- ── 2. Resultados agregados ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS obs360.resultados (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corrida_id   BIGINT NOT NULL REFERENCES obs360.corridas(id) ON DELETE CASCADE,
    nivel        TEXT NOT NULL,        -- 'secundaria' | 'primaria' | 'cuidadores' |
                                       -- 'triangulacion' (solo el cargador la lee)
    tipo         TEXT NOT NULL,        -- 'descriptivo' | 'banda' | 'corte' |
                                       -- 'correlacion' | 'grupo' | 'modelo' |
                                       -- 'fiabilidad' | 'tercil' | 'percentil' |
                                       -- 'item' | 'icc' | 'contraste'
    clave        TEXT NOT NULL,        -- p. ej. 'SDQ_Total'
    escala       TEXT,                 -- etiqueta legible
    agrupacion   TEXT,                 -- 'total' | 'Sexo' | 'Grado' | 'Colegio'
    grupo        TEXT,                 -- valor del grupo, o NULL si es el total
    n            INTEGER NOT NULL,
    valor        DOUBLE PRECISION,     -- la cifra principal (media, %, rho, β…)
    ic_inf       DOUBLE PRECISION,
    ic_sup       DOUBLE PRECISION,
    detalle      JSONB NOT NULL DEFAULT '{}'::jsonb,
    creada_en    TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- La regla de privacidad, impuesta por la base de datos
    CONSTRAINT resultados_min_grupo CHECK (n >= obs360.min_grupo()),
    CONSTRAINT resultados_nivel_valido
        CHECK (nivel IN ('secundaria', 'primaria', 'cuidadores', 'triangulacion')),
    -- Ninguna columna puede contener un identificador de estudiante (E),
    -- cuidador (C) ni niño (N)
    CONSTRAINT resultados_sin_id_estudiante CHECK (
        (grupo IS NULL OR grupo !~* '^[ECN][0-9a-f]{8}$')
        AND clave !~* '^[ECN][0-9a-f]{8}$'
    )
);

-- En una base creada antes de 2026-10-07 el CREATE TABLE IF NOT EXISTS no toca
-- las restricciones: se reemplazan aquí para que coincidan con las de arriba.
ALTER TABLE obs360.resultados DROP CONSTRAINT IF EXISTS resultados_nivel_valido;
ALTER TABLE obs360.resultados ADD CONSTRAINT resultados_nivel_valido
    CHECK (nivel IN ('secundaria', 'primaria', 'cuidadores', 'triangulacion'));
ALTER TABLE obs360.resultados DROP CONSTRAINT IF EXISTS resultados_sin_id_estudiante;
ALTER TABLE obs360.resultados ADD CONSTRAINT resultados_sin_id_estudiante CHECK (
    (grupo IS NULL OR grupo !~* '^[ECN][0-9a-f]{8}$')
    AND clave !~* '^[ECN][0-9a-f]{8}$');

-- Migración 2026-10-07c: ningún conteo de casos y alertas con estado solo donde
-- hay cifra. NOT VALID: no revisa las filas de corridas viejas, sí las nuevas.
ALTER TABLE obs360.resultados DROP CONSTRAINT IF EXISTS resultados_sin_conteos;
ALTER TABLE obs360.resultados ADD CONSTRAINT resultados_sin_conteos CHECK (
    NOT (detalle ?| ARRAY['casos', 'k_bajo', 'k_alto'])) NOT VALID;
ALTER TABLE obs360.resultados DROP CONSTRAINT IF EXISTS resultados_alerta_estado_con_cifra;
ALTER TABLE obs360.resultados ADD CONSTRAINT resultados_alerta_estado_con_cifra CHECK (
    tipo NOT LIKE 'alerta%'
    OR valor IS NOT NULL
    OR coalesce(detalle->>'estado', 'sin_estado') = 'sin_estado') NOT VALID;

COMMENT ON TABLE obs360.resultados IS
  'Resultados agregados listos para mostrar. Una fila = una cifra con su '
  'intervalo y su grupo. El CHECK de n >= min_grupo() hace imposible publicar '
  'un grupo reidentificable, aunque la aplicación tuviera un error.';
COMMENT ON COLUMN obs360.resultados.detalle IS
  'Campos propios de cada tipo: bandas (pct_b0..3), modelos (beta, se, p), '
  'cortes (fuente, umbral), correlaciones (variable_b, q_bh).';

CREATE INDEX IF NOT EXISTS resultados_corrida_idx
    ON obs360.resultados (corrida_id);
CREATE INDEX IF NOT EXISTS resultados_busqueda_idx
    ON obs360.resultados (nivel, tipo, clave);
CREATE INDEX IF NOT EXISTS resultados_grupo_idx
    ON obs360.resultados (agrupacion, grupo);

-- ── 3. Textos por audiencia ────────────────────────────────────────────────
-- Los mensajes que lee la comunidad se versionan aquí para que el equipo pueda
-- revisarlos sin tocar código, y para que quede registro de qué se dijo.
CREATE TABLE IF NOT EXISTS obs360.mensajes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modulo       TEXT NOT NULL DEFAULT 'estudiantes',
    clave        TEXT NOT NULL,
    titulo       TEXT NOT NULL,
    significa    TEXT NOT NULL,
    accion_rol   TEXT NOT NULL,        -- 'colegio' | 'familia' | 'municipio'
    accion       TEXT NOT NULL,
    revisado_por TEXT,
    revisado_en  DATE,
    vigente      BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT mensajes_rol_valido
        CHECK (accion_rol IN ('colegio', 'familia', 'municipio')),
    CONSTRAINT mensajes_unicos UNIQUE (modulo, clave, accion_rol)
);

-- Mensajes por módulo en una base creada antes de 2026-10-07.
ALTER TABLE obs360.mensajes ADD COLUMN IF NOT EXISTS modulo TEXT NOT NULL DEFAULT 'estudiantes';
ALTER TABLE obs360.mensajes DROP CONSTRAINT IF EXISTS mensajes_unicos;
ALTER TABLE obs360.mensajes ADD CONSTRAINT mensajes_unicos UNIQUE (modulo, clave, accion_rol);

COMMENT ON TABLE obs360.mensajes IS
  'Textos fijos de la vista comunidad. No los genera la IA: un texto sobre '
  'salud mental infantil lo revisa una persona y queda firmado en '
  'revisado_por / revisado_en.';

-- ── 4. Row Level Security ──────────────────────────────────────────────────
ALTER TABLE obs360.corridas   ENABLE ROW LEVEL SECURITY;
ALTER TABLE obs360.resultados ENABLE ROW LEVEL SECURITY;
ALTER TABLE obs360.mensajes   ENABLE ROW LEVEL SECURITY;

-- ¿Es esta la última corrida publicada de su módulo?
-- SECURITY DEFINER: la política de `corridas` llama a esta función, y la función
-- lee `corridas`; sin SECURITY DEFINER la política se evaluaría a sí misma (y
-- `anon` solo vería la fila que ya pasó el filtro). Corre con los permisos de su
-- dueño, que debe saltarse RLS: desde el SQL Editor el dueño es `postgres`
-- (dueño de las tablas, por lo tanto exento de RLS). Se fija explícito abajo.
-- `search_path` fijo para que nadie sustituya objetos con un esquema propio.
-- Va antes de las políticas que la usan, y en un esquema que la API REST no
-- expone (`obs360_interno`): así nadie la puede llamar como /rpc desde fuera.
CREATE SCHEMA IF NOT EXISTS obs360_interno;
REVOKE ALL ON SCHEMA obs360_interno FROM PUBLIC;
GRANT USAGE ON SCHEMA obs360_interno TO anon, authenticated, service_role;
DROP FUNCTION IF EXISTS obs360.es_ultima_publicada(bigint) CASCADE;
CREATE OR REPLACE FUNCTION obs360_interno.es_ultima_publicada(p_id bigint) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = obs360, pg_temp AS $$
  SELECT p_id = (SELECT c.id FROM obs360.corridas c
                 WHERE c.publicada
                   AND c.modulo = (SELECT m.modulo FROM obs360.corridas m
                                   WHERE m.id = p_id)
                 ORDER BY c.creada_en DESC, c.id DESC LIMIT 1);
$$;
ALTER FUNCTION obs360_interno.es_ultima_publicada(bigint) OWNER TO postgres;
REVOKE ALL ON FUNCTION obs360_interno.es_ultima_publicada(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION obs360_interno.es_ultima_publicada(bigint)
    TO anon, authenticated, service_role;

-- ¿Puede el público leer esta corrida? La última publicada de su módulo Y que no
-- sea de triangulación (migración 2026-10-10b): la triangulación es solo para el
-- equipo investigador y la lee únicamente el usuario de carga. Mismo blindaje
-- que `es_ultima_publicada`.
CREATE OR REPLACE FUNCTION obs360_interno.es_publica(p_id bigint) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = obs360, pg_temp AS $$
  SELECT coalesce(
    EXISTS (SELECT 1 FROM obs360.corridas m
            WHERE m.id = p_id
              AND lower(btrim(m.modulo)) <> 'triangulacion')
    AND obs360_interno.es_ultima_publicada(p_id),
    false);
$$;
ALTER FUNCTION obs360_interno.es_publica(bigint) OWNER TO postgres;
REVOKE ALL ON FUNCTION obs360_interno.es_publica(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION obs360_interno.es_publica(bigint)
    TO anon, authenticated, service_role;

-- Anónimo: solo lectura, y solo de la ÚLTIMA corrida publicada de cada módulo,
-- nunca de triangulación. Una corrida vieja que siga marcada como publicada no
-- se lee.
DROP POLICY IF EXISTS "lectura publica de corridas publicadas" ON obs360.corridas;
CREATE POLICY "lectura publica de corridas publicadas" ON obs360.corridas
    FOR SELECT TO anon, authenticated USING (obs360_interno.es_publica(id));

DROP POLICY IF EXISTS "lectura publica de resultados publicados" ON obs360.resultados;
CREATE POLICY "lectura publica de resultados publicados" ON obs360.resultados
    FOR SELECT TO anon, authenticated
    USING (obs360_interno.es_publica(corrida_id) AND nivel <> 'triangulacion');

-- Usuario de carga (app_metadata.obs360_rol = 'cargador', solo en los secretos
-- del despliegue privado): lee CUALQUIER corrida y sus resultados, publicada o
-- no, para la vista previa del equipo (migración 2026-10-10). Solo SELECT; se
-- suma con OR a la política pública, que no cambia. La función es la misma de
-- supabase/almacen_schema.sql; se define aquí para no depender del orden.
CREATE OR REPLACE FUNCTION obs360.es_cargador() RETURNS boolean
LANGUAGE sql STABLE SET search_path = obs360, pg_temp AS $$
    SELECT coalesce((auth.jwt() -> 'app_metadata' ->> 'obs360_rol') = 'cargador', false)
$$;

DROP POLICY IF EXISTS "cargador lee todas las corridas" ON obs360.corridas;
CREATE POLICY "cargador lee todas las corridas" ON obs360.corridas
    FOR SELECT TO authenticated USING (obs360.es_cargador());

DROP POLICY IF EXISTS "cargador lee todos los resultados" ON obs360.resultados;
CREATE POLICY "cargador lee todos los resultados" ON obs360.resultados
    FOR SELECT TO authenticated USING (obs360.es_cargador());

DROP POLICY IF EXISTS "lectura publica de mensajes vigentes" ON obs360.mensajes;
CREATE POLICY "lectura publica de mensajes vigentes" ON obs360.mensajes
    FOR SELECT TO anon, authenticated
    USING (vigente = true);

-- No se crea ninguna política de INSERT, UPDATE o DELETE para anon ni para
-- authenticated. Sin política, RLS lo niega: escribir exige service_role, que
-- salta RLS y se queda en el equipo que publica. Es deliberado.

-- Permisos de esquema: el rol anónimo puede mirar, no puede tocar.
GRANT USAGE ON SCHEMA obs360 TO anon, authenticated;
GRANT SELECT ON obs360.corridas, obs360.resultados, obs360.mensajes
    TO anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON obs360.corridas, obs360.resultados,
    obs360.mensajes FROM anon, authenticated;

-- El rol de servicio sí escribe: es el que usa el publicador desde el equipo de
-- quien procesa. Salta RLS, pero aun así necesita permisos de esquema y tabla.
GRANT USAGE ON SCHEMA obs360 TO service_role, postgres;
GRANT ALL ON ALL TABLES IN SCHEMA obs360 TO service_role, postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA obs360 TO service_role, postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA obs360
    GRANT ALL ON TABLES TO service_role, postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA obs360
    GRANT ALL ON SEQUENCES TO service_role, postgres;

-- ── 5. Vistas de conveniencia ──────────────────────────────────────────────
-- Lo que la plataforma consulta: la última corrida publicada de CADA módulo
-- (una fila por módulo). Mismas columnas y orden que `corridas` (`*`):
-- CREATE OR REPLACE VIEW no admite quitar ni renombrar columnas.
CREATE OR REPLACE VIEW obs360.ultima_corrida
WITH (security_invoker = true) AS
SELECT DISTINCT ON (modulo) * FROM obs360.corridas
WHERE publicada = true
ORDER BY modulo, creada_en DESC, id DESC;

CREATE OR REPLACE VIEW obs360.resultados_vigentes
WITH (security_invoker = true) AS
SELECT r.*
FROM obs360.resultados r
JOIN obs360.ultima_corrida c ON c.id = r.corrida_id;

COMMENT ON VIEW obs360.resultados_vigentes IS
  'Resultados de la última corrida publicada de cada módulo. `security_invoker` hace que la '
  'vista respete las políticas RLS de quien consulta, en lugar de saltárselas.';

GRANT SELECT ON obs360.ultima_corrida, obs360.resultados_vigentes
    TO anon, authenticated, service_role;

-- ── 6. Higiene de lo que ya existía ────────────────────────────────────────
-- La tabla `processed_data` se creó con inserción y lectura anónimas abiertas:
-- cualquiera con la clave del cliente podía escribir en ella. Se cierra la
-- escritura y se deja la lectura, que es lo que la aplicación necesita.
DO $$
DECLARE
  pol RECORD;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables
             WHERE schemaname = 'public' AND tablename = 'processed_data') THEN
    EXECUTE 'ALTER TABLE public.processed_data ENABLE ROW LEVEL SECURITY';
    -- Se eliminan TODAS las políticas de escritura, sin depender de su nombre:
    -- había dos con nombres distintos y una se quedó abierta por eso.
    FOR pol IN
      SELECT policyname FROM pg_policies
      WHERE schemaname = 'public' AND tablename = 'processed_data'
        AND cmd IN ('INSERT', 'UPDATE', 'DELETE')
    LOOP
      EXECUTE format('DROP POLICY %I ON public.processed_data', pol.policyname);
      RAISE NOTICE 'processed_data: política de escritura eliminada (%)', pol.policyname;
    END LOOP;
    EXECUTE 'REVOKE INSERT, UPDATE, DELETE ON public.processed_data FROM anon, authenticated';
    RAISE NOTICE 'processed_data: escritura anónima revocada; lectura intacta.';
  END IF;
END $$;

-- ── 7. Comprobación ────────────────────────────────────────────────────────
-- Debe devolver rowsecurity = true en las tres tablas y ninguna política de
-- escritura para anon.
--
--   SELECT tablename, rowsecurity FROM pg_tables WHERE schemaname = 'obs360';
--   SELECT tablename, policyname, cmd, roles FROM pg_policies
--    WHERE schemaname = 'obs360' ORDER BY tablename, cmd;
