-- Create the table for processed data
-- We use a flexible JSONB column 'data' to store the row content, allowing for schema evolution.
CREATE TABLE IF NOT EXISTS processed_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    data JSONB, -- Stores the entire row as a JSON object
    filename TEXT, -- To track which file this row came from
    processed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE processed_data ENABLE ROW LEVEL SECURITY;

-- Policy to allow anonymous inserts (for development/public access if needed, or authenticated)
-- Adjust 'anon' to 'authenticated' if you require login.
DROP POLICY IF EXISTS "Allow anonymous inserts" ON processed_data;
CREATE POLICY "Allow anonymous inserts" ON processed_data
    FOR INSERT 
    TO anon 
    WITH CHECK (true);

-- Policy to allow anonymous reads
DROP POLICY IF EXISTS "Allow anonymous select" ON processed_data;
CREATE POLICY "Allow anonymous select" ON processed_data
    FOR SELECT 
    TO anon 
    USING (true);

-- Storage Bucket Setup (You might need to do this in the Dashboard if SQL doesn't support it directly in your plan)
-- INSERT INTO storage.buckets (id, name, public) VALUES ('datasets', 'datasets', true);
